### PR TITLE
Add class ParseApp

### PR DESCRIPTION
**Pull request by phelipealves**

### CODE REVIEW

**Comment by gfosco** [comment]
Interesting... I like it, but these endpoints (which I assume you got from the CLI) are unsupported in this method.  I'd rather see it use the account key format, rather than encouraging the use of the account password.  Any chance you're willing to update it to use account keys instead? `X-Parse-Account-Key`

**Comment by phelipealves** [comment]
Tanks @gfosco .
Updated. Take a look.

**Comment by phelipealves** [comment]
@gfosco

**Comment by gfosco** [comment]
Looks good to me.  Go ahead and rebase.

**Comment by phelipealves** [comment]
@gfosco rebase finalized :+1:

**Pull request merged**
