### PR TITLE
PSR2 half way compliance

### PR DESCRIPTION
**Pull request by juliangut**
PSR max compliance level possible without changing property and method "_" names

*The list of non PSR compliant files*
```
ParseFile.php:163 - Method name "_createFromServer" should not be prefixed with an underscore to indicate visibility
ParseFile.php:177 - Method name "_encode" should not be prefixed with an underscore to indicate visibility
ParseBytes.php:65 - Method name "_encode" should not be prefixed with an underscore to indicate visibility
ParseClient.php:116 - Method name "_encode" should not be prefixed with an underscore to indicate visibility
ParseClient.php:158 - Method name "_decode" should not be prefixed with an underscore to indicate visibility
ParseClient.php:226 - Method name "_encodeArray" should not be prefixed with an underscore to indicate visibility
ParseClient.php:249 - Method name "_request" should not be prefixed with an underscore to indicate visibility
ParseClient.php:341 - Method name "_unsetStorage" should not be prefixed with an underscore to indicate visibility
ParseClient.php:361 - Method name "_getRequestHeaders" should not be prefixed with an underscore to indicate visibility
ParseQuery.php:240 - Method name "_getOptions" should not be prefixed with an underscore to indicate visibility
ParseQuery.php:754 - Method name "_or" should not be prefixed with an underscore to indicate visibility
ParseObject.php:259 - Method name "_isDirty" should not be prefixed with an underscore to indicate visibility
ParseObject.php:406 - Method name "_performOperation" should not be prefixed with an underscore to indicate visibility
ParseObject.php:469 - Method name "_isDataAvailable" should not be prefixed with an underscore to indicate visibility
ParseObject.php:597 - Method name "_mergeAfterFetch" should not be prefixed with an underscore to indicate visibility
ParseObject.php:621 - Method name "_mergeAfterFetchWithSelectedKeys" should not be prefixed with an underscore to indicate visibility
ParseObject.php:688 - Method name "_mergeMagicFields" should not be prefixed with an underscore to indicate visibility
ParseObject.php:908 - Method name "_encode" should not be prefixed with an underscore to indicate visibility
ParseObject.php:1260 - Method name "_toPointer" should not be prefixed with an underscore to indicate visibility
ParseObject.php:1329 - Method name "_unregisterSubclass" should not be prefixed with an underscore to indicate visibility
ParseSession.php:14 - Property name "$_sessionToken" should not be prefixed with an underscore to indicate visibility
ParseSession.php:66 - Method name "_isRevocable" should not be prefixed with an underscore to indicate visibility
ParseUser.php:26 - Property name "$_sessionToken" should not be prefixed with an underscore to indicate visibility
ParseUser.php:432 - Method name "_clearCurrentUserVariable" should not be prefixed with an underscore to indicate visibility
ParseGeoPoint.php:95 - Method name "_encode" should not be prefixed with an underscore to indicate visibility
Internal/IncrementOperation.php:46 - Method name "_encode" should not be prefixed with an underscore to indicate visibility
Internal/IncrementOperation.php:62 - Method name "_apply" should not be prefixed with an underscore to indicate visibility
Internal/IncrementOperation.php:81 - Method name "_mergeWithPrevious" should not be prefixed with an underscore to indicate visibility
Internal/ParseRelationOperation.php:131 - Method name "_apply" should not be prefixed with an underscore to indicate visibility
Internal/ParseRelationOperation.php:162 - Method name "_mergeWithPrevious" should not be prefixed with an underscore to indicate visibility
Internal/ParseRelationOperation.php:224 - Method name "_encode" should not be prefixed with an underscore to indicate visibility
Internal/ParseRelationOperation.php:256 - Method name "_getTargetClass" should not be prefixed with an underscore to indicate visibility
Internal/AddOperation.php:52 - Method name "_encode" should not be prefixed with an underscore to indicate visibility
Internal/AddOperation.php:67 - Method name "_mergeWithPrevious" should not be prefixed with an underscore to indicate visibility
Internal/AddOperation.php:103 - Method name "_apply" should not be prefixed with an underscore to indicate visibility
Internal/FieldOperation.php:21 - Method name "_apply" should not be prefixed with an underscore to indicate visibility
Internal/FieldOperation.php:31 - Method name "_mergeWithPrevious" should not be prefixed with an underscore to indicate visibility
Internal/DeleteOperation.php:17 - Method name "_encode" should not be prefixed with an underscore to indicate visibility
Internal/DeleteOperation.php:31 - Method name "_apply" should not be prefixed with an underscore to indicate visibility
Internal/DeleteOperation.php:43 - Method name "_mergeWithPrevious" should not be prefixed with an underscore to indicate visibility
Internal/RemoveOperation.php:54 - Method name "_encode" should not be prefixed with an underscore to indicate visibility
Internal/RemoveOperation.php:69 - Method name "_mergeWithPrevious" should not be prefixed with an underscore to indicate visibility
Internal/RemoveOperation.php:103 - Method name "_apply" should not be prefixed with an underscore to indicate visibility
Internal/Encodable.php:18 - Method name "_encode" should not be prefixed with an underscore to indicate visibility
Internal/SetOperation.php:55 - Method name "_encode" should not be prefixed with an underscore to indicate visibility
Internal/SetOperation.php:78 - Method name "_apply" should not be prefixed with an underscore to indicate visibility
Internal/SetOperation.php:91 - Method name "_mergeWithPrevious" should not be prefixed with an underscore to indicate visibility
Internal/AddUniqueOperation.php:52 - Method name "_encode" should not be prefixed with an underscore to indicate visibility
Internal/AddUniqueOperation.php:67 - Method name "_mergeWithPrevious" should not be prefixed with an underscore to indicate visibility
Internal/AddUniqueOperation.php:101 - Method name "_apply" should not be prefixed with an underscore to indicate visibility
ParseACL.php:76 - Method name "_createACLFromJSON" should not be prefixed with an underscore to indicate visibility
ParseACL.php:106 - Method name "_isShared" should not be prefixed with an underscore to indicate visibility
ParseACL.php:116 - Method name "_setShared" should not be prefixed with an underscore to indicate visibility
ParseACL.php:121 - Method name "_encode" should not be prefixed with an underscore to indicate visibility
ParseACL.php:542 - Method name "_getDefaultACL" should not be prefixed with an underscore to indicate visibility
ParseAnalytics.php:65 - Method name "_toSaveJSON" should not be prefixed with an underscore to indicate visibility
```

### CODE REVIEW

**Comment by gfosco** [comment]
Since I merged #161 can you rebase this for anything missing?

**Comment by juliangut** [comment]
That's a lot to verify for conflicts as we both have change quoting style, I'll try to find some time for it ASAP

**Comment by gfosco** [comment]
If you do get a chance, lets review in a new PR.  Thanks! :+1:

**Comment by juliangut** [comment]
Yep, I forgot about this ;(

**Pull request closed without merging**
