### PR TITLE
PSR-2

### PR DESCRIPTION
**Pull request by HipsterJazzbo**
As discussed in #79

### CODE REVIEW

**Comment by HipsterJazzbo** [comment]
@gfosco Any chance of getting this merged soon? I've got one more PR that fixes #42 and then I can release this sweet Laravel integration package I've written :)

**Comment by HipsterJazzbo** [comment]
@gfosco @GrahamCampbell *knock knock* This thing on?

**Comment by gfosco** [comment]
Sorry, I didn't get to this in time (reviewing it is a pain due to the widespread changes...) and we added the Sessions API last week, so this can't be merged now.  I will use Style CI and submit a new PR.

**Comment by HipsterJazzbo** [comment]
Awesome! I've got a PR that fixes user subclassing, but I did in PSR-2 so when you've done that I'll open it up. Thanks!

**Comment by gfosco** [comment]
Merged #83.  Thanks again for your contributions

**Comment by gfosco** [comment]
Also, StyleCI is enabled for the repo, and all future PRs will be checked. :)

**Comment by GrahamCampbell** [comment]
StyleCI didn't do a good job of the indentation changes. You should have really done that first, then let styleci do the rest.

**Comment by HipsterJazzbo** [comment]
@GrahamCampbell Yeah I noticed that, but this has been done and merged separately by @gfosco in #83

**Comment by GrahamCampbell** [comment]
@HipsterJazzbo That had to be reverted...

**Comment by GrahamCampbell** [comment]
See https://github.com/ParsePlatform/parse-php-sdk/pull/87.

**Comment by GrahamCampbell** [comment]
and https://github.com/ParsePlatform/parse-php-sdk/pull/88

**Pull request closed without merging**
